apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2023-12-12T14:42:26Z"
  generation: 13
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: ecf0b3c1-1661-4aed-999e-ffc71eef310f
  resourceVersion: "829961"
  uid: 294af425-4a00-448b-b614-149d7859362e
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd-esky
    mappingMethod: claim
    name: htpasswd_esky
    type: HTPasswd
  - ldap:
      attributes:
        email: []
        id:
        - sAMAccountName
        name:
        - displayName
        preferredUsername:
        - sAMAccountName
      bindDN: administrator@lab.fahmy
      bindPassword:
        name: ldap-bind-password-n74qm
      ca:
        name: ldap-ca-d9qzp
      insecure: false
      url: ldap://dns02.lab.fahmy/OU=OpenShift,DC=lab,DC=fahmy?sAMAccountName
    mappingMethod: claim
    name: ldap
    type: LDAP
